#!/usr/bin/env python3
"""Build the deterministic BAFTA unresolved-work identity review report."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from bafta_common import SOURCE_DIR, load_json


ROOT = Path(__file__).resolve().parents[1]
IDENTITY_MAP_PATH = SOURCE_DIR / "identity-map.json"
REPORT_PATH = ROOT / "reports" / "bafta-identity-review.md"


def escaped(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def candidate_link(candidate: dict) -> str:
    media_path = "tv" if candidate["mediaType"] == "series" else "movie"
    label = f"{candidate['mediaType']} TMDB {candidate['tmdbId']}"
    if candidate.get("imdbId"):
        label += f" / {candidate['imdbId']}"
    year = candidate.get("releaseYear")
    title = candidate["title"] + (f" ({year})" if year else "")
    return (
        f"[{escaped(label)}](https://www.themoviedb.org/{media_path}/{candidate['tmdbId']}) "
        f"{escaped(title)}"
    )


def unresolved_kind(entry: dict) -> str:
    candidates = entry.get("candidates", [])
    if not candidates:
        return "no-exact-candidate"
    plausible = [
        candidate
        for candidate in candidates
        if candidate.get("awardWindowPlausible") and candidate.get("imdbId")
    ]
    if len(plausible) > 1:
        return "ambiguous"
    return "candidate-rejected"


def evidence(entry: dict) -> str:
    candidates = entry.get("candidates", [])
    if not candidates:
        return "No exact-title TMDB candidate"
    values = []
    for candidate in candidates[:4]:
        flags = []
        if not candidate.get("awardWindowPlausible"):
            flags.append("outside award window")
        if not candidate.get("imdbId"):
            flags.append("no IMDb ID")
        suffix = f" — {', '.join(flags)}" if flags else ""
        values.append(candidate_link(candidate) + suffix)
    return "<br>".join(values)


def report_content(identity_map: dict) -> str:
    works = identity_map["works"]
    resolved = [entry for entry in works if "resolution" in entry]
    unresolved = [entry for entry in works if "resolution" not in entry]
    groups = {
        "no-exact-candidate": [],
        "ambiguous": [],
        "candidate-rejected": [],
    }
    for entry in unresolved:
        groups[unresolved_kind(entry)].append(entry)
    movies = sum(entry["resolution"]["mediaType"] == "movie" for entry in resolved)
    series = sum(entry["resolution"]["mediaType"] == "series" for entry in resolved)
    unattempted = sum("candidates" not in entry for entry in unresolved)
    lines = [
        "# BAFTA work identity review",
        "",
        "> Generated by `python scripts/build_bafta_identity_review.py --write`. Do not edit manually.",
        "",
        "The committed BAFTA snapshots decide award facts. This report inventories only work identity and media-classification review; TMDB does not decide winner status.",
        "",
        "## Summary",
        "",
        f"- Selected work-linked winner records: **{identity_map['selectedWinnerRecords']:,}**",
        f"- Award-year-scoped work identities: **{len(works):,}**",
        f"- Resolved identities: **{len(resolved):,}** ({movies:,} movies; {series:,} series)",
        f"- Unresolved identities: **{len(unresolved):,}**",
        f"- Unattempted identities: **{unattempted:,}**",
        f"- No exact-title candidate: **{len(groups['no-exact-candidate']):,}**",
        f"- Multiple plausible exact-title candidates: **{len(groups['ambiguous']):,}**",
        f"- Candidate evidence without an acceptable IMDb/date relationship: **{len(groups['candidate-rejected']):,}**",
        "",
    ]
    sections = (
        (
            "Multiple plausible candidates",
            "ambiguous",
            "Each row has more than one exact-title candidate inside the award window and needs an explicit reviewed choice.",
        ),
        (
            "No exact-title candidate",
            "no-exact-candidate",
            "These commonly need a title alias, parent-series relationship, event/episode reconciliation, or a documented non-catalogue outcome.",
        ),
        (
            "Candidate evidence rejected by the automatic contract",
            "candidate-rejected",
            "These candidates lack a usable IMDb ID or fall outside the accepted award window and require explicit review.",
        ),
    )
    for heading, key, description in sections:
        entries = groups[key]
        lines.extend(
            [
                f"## {heading} ({len(entries):,})",
                "",
                description,
                "",
                "| Source work | Context | Candidate evidence |",
                "| --- | --- | --- |",
            ]
        )
        for entry in entries:
            source = " / ".join(escaped(title) for title in entry["titles"])
            context = (
                f"{escaped(', '.join(entry['programmes']))}; "
                f"award {escaped(', '.join(str(year) for year in entry['years']))}; "
                f"{escaped(', '.join(entry['categoryIds']))}; "
                f"nomination {escaped(', '.join(entry['nominationIds']))}"
            )
            lines.append(f"| {source} | {context} | {evidence(entry)} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not (args.write or args.check):
        parser.error("choose --write or --check")
    try:
        content = report_content(load_json(IDENTITY_MAP_PATH))
        if args.write:
            REPORT_PATH.write_text(content, encoding="utf-8")
        if args.check and (
            not REPORT_PATH.is_file() or REPORT_PATH.read_text(encoding="utf-8") != content
        ):
            raise ValueError("BAFTA identity review report is stale")
        print(f"BAFTA identity review report is current: {REPORT_PATH.relative_to(ROOT)}")
        return 0
    except (KeyError, OSError, TypeError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
